## Hill Cipher

The Hill Cipher is a variant of the Affine ciphers. It uses a 2x2 or 3x3 matrix (linear algebra) to encrypt messages in batches of 2 or 3 letters. 

For example, we use a 2x2 matrix as the key, 

$$
{\cal K}=
\begin{pmatrix}
Z & A \\
C & H 
\end{pmatrix}
$$

to encrypt the message 'CODEBUSTERS'. The message is grouped in pairs "CO DE BU ST ER S**Z**". Notice that a Z is added in order to make the last group a group of two. 

We use the value for each letter as following,

|Letters  | A| B| C| D| E| F| G| H| I| J| K| L| M| N| O| P| Q| R| S| T| U| V| W| X| Y| Z|
|:-------:|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|
|Numbers  | 0| 1| 2| 3| 4| 5| 6| 7| 8| 9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|


to encrypt 'CO'

$$
\begin{pmatrix}
Z & A \\
C & H 
\end{pmatrix}
\begin{pmatrix}
C \\
O 
\end{pmatrix}
=
\begin{pmatrix}
25 & 0 \\
2 & 7 
\end{pmatrix}
\begin{pmatrix}
2 \\
14 
\end{pmatrix}
=\begin{pmatrix}
50 \\
102
\end{pmatrix}
\pmod {26}
=\begin{pmatrix}
24 \\
24
\end{pmatrix}
=\begin{pmatrix}
Y \\
Y
\end{pmatrix}
$$

The cipher text is therefore 'YY'. 


To decrypt the ciphertext, we need to know the (modular multiplicative) inverse matrix of the encryption key, i.e., 
${\cal K}^{-1} {\cal K} \mod (26) = I$, where $I$ is the identity matrix. More details and the methods to solve the 
modular multiplicative inverse matrix are provided in the [Modular Inversion](../Modular/Readme.ipynb), where we also show the solutions for this example. The inverse matrix is found to be 

$$ 
{\cal K}^{-1} = 
\begin{pmatrix}
25 & 0 \\
4 & 15 
\end{pmatrix}
$$

to decrypt 'YY', 

$$
\begin{pmatrix}
25 & 0 \\
4 & 15 
\end{pmatrix}
\begin{pmatrix}
-2 \\
-2 
\end{pmatrix}
=
\begin{pmatrix}
-50 \\
-38 
\end{pmatrix} \pmod{26} 
=\begin{pmatrix}
2 \\
14 
\end{pmatrix}=
\begin{pmatrix}
C \\
O 
\end{pmatrix}
$$ 


### Examples 

There are some examples at the Python Utilities section below. The Hill Cipher is not so difficult as long as you are familiar with linear algebra, and modular arithmetic. It just takes a long time to do all the calculations. I will not go through the detailed steps of the encyption/decryption.  

The most difficult part is to compute the modular multiplicative inverse matrix. You are required to do it when e.g., being asked to decrypt a message but the encryption matrix is given; to encrypt a message but the decryption key is given. You may follow the standard procedure by calculating its determinant and its adjugate matrix. Or, I have found that the Gaussian elimination procedure is easier and faster. See [Modular Inversion](../Modular/Readme.ipynb) for instructions and examples, where step-by-step instructions are provided. 

For a Hill Cipher problem in Codebusters, either the encryption or the decryption key has to be provided. Otherwise, decrypting the ciphertext is not human solvable. With computers, one might be able to search the key space for small matrices, e.g., 2x2, there are at most $26^4$ keys. Note that not all matrices serve as Hill Cipher keys; it needs to be modular invertible, or its determinant needs to be coprime with 26. This limits the key space. 

Note also, the key might be provided as a 4 or 9 letter keyword, instead of a matrix. 

### Python Utilities

Various routines are developed for Hill Cipher. See [Python code](HillCipher.py) for details. 

In [1]:
### Create a 3x3 Hill Cipher and Encrypt/Decrypt a message
from HillCipher import *

#### create a random 3x3 matrix as key
cipherKey = keyGenerator(size=3)
# print the key
print("The key is")
print(cipherKey)

#### to encrypt a message
# plain text to be encrypted
plaintext = "It's a wonderful life"
# encrypt the plain text
ciphertext = encrypt(plaintext, cipherKey)
# print the cipher text
print("Ciphertext    :", ciphertext)

#### to decrypt a cipher text, if needed
# get the modular multiplicative inverse for the decipher key
decipherKey = modInverseMatrix(cipherKey)
# print the decipher key
print("The Decipher Key is")
print(decipherKey)
# decrypt with the decipher key
decrypted = decrypt(ciphertext, decipherKey)
# print the decrypted message
print("Decrypted text:", decrypted)

cipherKey.dot(decipherKey) % 26

The key is
[[ 1 21 11]
 [ 2 15 19]
 [20 13 20]]
Ciphertext    : HT'N S YUQRPEVZS BDAZC
The Decipher Key is
[[11 21  0]
 [22 10  7]
 [ 2  5 15]]
Decrypted text: IT'S A WONDERFUL LIFEZ


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [2]:
### Create a 2x2 Hill Cipher and Encrypt/Decrypt a message
from HillCipher import *

#### create a random 2x2 matrix as key
cipherKey = keyGenerator(size=2)
# print the key
print("The key is")
print(cipherKey)

#### to encrypt a message
# plain text to be encrypted
plaintext = "It's a wonderful life"
# encrypt the plain text
ciphertext = encrypt(plaintext, cipherKey)
# print the cipher text
print("Ciphertext    :", ciphertext)

#### to decrypt a cipher text, if needed
# get the modular multiplicative inverse for the decipher key
decipherKey = modInverseMatrix(cipherKey)
# print the decipher key
print("The Decipher Key is")
print(decipherKey)
# decrypt with the decipher key
decrypted = decrypt(ciphertext, decipherKey)
# print the decrypted message
print("Decrypted text:", decrypted)

cipherKey.dot(decipherKey) % 26

The key is
[[19 25]
 [24 13]]
Ciphertext    : DX'E Q OIKNHFXQQ RRXZF
The Decipher Key is
[[13 19]
 [12 23]]
Decrypted text: IT'S A WONDERFUL LIFEZ


array([[1, 0],
       [0, 1]])

#### Solve  Problem 5 in [scilympiad.com practice set](https://scilympiad.com/data/org/sopractice/public/CodebustersCTest.StudentVersion_53.pdf) 

Decrypt the following ciphertext. It was encrypted using a Hill Cipher with the provided key...


$$ \begin{pmatrix}
6 & 24 & 1 \\
13 & 16 & 10 \\
20 & 17 & 15
\end{pmatrix}
$$

```
FGDIVCX BJTC IZNVI QMXYI LZ XI CUSU DJ GZ YGSM RP WAWU PV CN SRRT OGYUUDEKG

```



In [3]:
from HillCipher import *
# write the encryption as a numpy array
cipherKey = np.asarray([[6,24,1],[13,16,10],[20,17,15]])
# the cipher text
ciphertext = "FGDIVCX BJTC IZNVI QMXYI LZ XI CUSU DJ GZ YGSM RP WAWU PV CN SRRT OGYUUDEKG"

# to decrypt it, we first get the decryption key by modular inverse
decipherKey = modInverseMatrix(cipherKey)
# show it 
print("The Decipher Key is")
print(decipherKey)
# decrypt with the decipher key
decrypted = decrypt(ciphertext, decipherKey)
# print the decrypted message
print("Decrypted text:", decrypted)

The Decipher Key is
[[ 8  5 10]
 [21  8 21]
 [21 12  8]]
Decrypted text: WITHOUT EVIL THERE COULD BE NO GOOD SO IT MUST BE GOOD TO BE EVIL SOMETIMES


#### Solve  Problem 6 in [scilympiad.com practice set](https://scilympiad.com/data/org/sopractice/public/CodebustersCTest.StudentVersion_53.pdf) 

Encrypt the following plaintext using a Hill cipher with the decryption key below.

$$ \begin{pmatrix}
25 & 0 \\
2 & 7
\end{pmatrix}
$$

```
Softly call the muster let the comrade answer here
```

In [4]:
from HillCipher import *

# write the decryption as a numpy array
decipherKey = np.asarray([[25, 0],[2, 7]])

# since it's the decryption key, we need the encryption key by modular inverse
cipherKey = modInverseMatrix(decipherKey)
# show me the key
print("The Cipher Key is")
print(cipherKey)

# the plain text
plaintext = "Softly call the muster let the comrade answer here"

# encrypt with the cipher key
ciphertext = encrypt(plaintext, cipherKey)
# print the decrypted message
print("Plaintext :", plaintext)
print("Ciphertext:", ciphertext)

The Cipher Key is
[[25  0]
 [ 4 15]]
Plaintext : Softly call the muster let the comrade answer here
Ciphertext: IWVTPO YIPB HZW OGMHGJ ZWP HZW UMCJQXU ANIMWL TKJY
